/**
 * Daftar Resmi Kota dan Kabupaten di Indonesia (38 Provinsi)
 * Digunakan untuk dropdown pemilihan lokasi properti, filter pencarian, dan kontrak sewa.
 */

export interface CityOption {
  value: string;
  label: string;
  province: string;
  type: 'Kota' | 'Kabupaten';
}

export const INDONESIA_POPULAR_CITIES: string[] = [
  'Kota Jakarta Selatan',
  'Kota Jakarta Barat',
  'Kota Jakarta Pusat',
  'Kota Jakarta Timur',
  'Kota Jakarta Utara',
  'Kota Bandung',
  'Kabupaten Bandung',
  'Kabupaten Bandung Barat',
  'Kota Cimahi',
  'Kota Bekasi',
  'Kabupaten Bekasi',
  'Kota Depok',
  'Kota Bogor',
  'Kabupaten Bogor',
  'Kota Tangerang',
  'Kota Tangerang Selatan',
  'Kabupaten Tangerang',
  'Kota Surabaya',
  'Kota Malang',
  'Kota Semarang',
  'Kota Surakarta (Solo)',
  'Kota Yogyakarta',
  'Kabupaten Sleman',
  'Kabupaten Bantul',
  'Kota Denpasar',
  'Kabupaten Badung',
  'Kota Medan',
  'Kota Batam',
  'Kota Pekanbaru',
  'Kota Palembang',
  'Kota Bandar Lampung',
  'Kota Makassar',
  'Kota Balikpapan',
  'Kota Samarinda',
  'Kota Banjarmasin',
  'Kota Pontianak',
  'Kota Manado',
  'Kota Mataram',
];

export const INDONESIA_CITIES: CityOption[] = [
  // --- DKI JAKARTA ---
  { value: 'Kota Jakarta Selatan', label: 'Kota Jakarta Selatan', province: 'DKI Jakarta', type: 'Kota' },
  { value: 'Kota Jakarta Barat', label: 'Kota Jakarta Barat', province: 'DKI Jakarta', type: 'Kota' },
  { value: 'Kota Jakarta Pusat', label: 'Kota Jakarta Pusat', province: 'DKI Jakarta', type: 'Kota' },
  { value: 'Kota Jakarta Timur', label: 'Kota Jakarta Timur', province: 'DKI Jakarta', type: 'Kota' },
  { value: 'Kota Jakarta Utara', label: 'Kota Jakarta Utara', province: 'DKI Jakarta', type: 'Kota' },
  { value: 'Kabupaten Kepulauan Seribu', label: 'Kabupaten Kepulauan Seribu', province: 'DKI Jakarta', type: 'Kabupaten' },

  // --- JAWA BARAT ---
  { value: 'Kota Bandung', label: 'Kota Bandung', province: 'Jawa Barat', type: 'Kota' },
  { value: 'Kabupaten Bandung', label: 'Kabupaten Bandung', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Bandung Barat', label: 'Kabupaten Bandung Barat', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kota Bekasi', label: 'Kota Bekasi', province: 'Jawa Barat', type: 'Kota' },
  { value: 'Kabupaten Bekasi', label: 'Kabupaten Bekasi', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kota Bogor', label: 'Kota Bogor', province: 'Jawa Barat', type: 'Kota' },
  { value: 'Kabupaten Bogor', label: 'Kabupaten Bogor', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kota Cimahi', label: 'Kota Cimahi', province: 'Jawa Barat', type: 'Kota' },
  { value: 'Kota Cirebon', label: 'Kota Cirebon', province: 'Jawa Barat', type: 'Kota' },
  { value: 'Kabupaten Cirebon', label: 'Kabupaten Cirebon', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kota Depok', label: 'Kota Depok', province: 'Jawa Barat', type: 'Kota' },
  { value: 'Kota Sukabumi', label: 'Kota Sukabumi', province: 'Jawa Barat', type: 'Kota' },
  { value: 'Kabupaten Sukabumi', label: 'Kabupaten Sukabumi', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kota Tasikmalaya', label: 'Kota Tasikmalaya', province: 'Jawa Barat', type: 'Kota' },
  { value: 'Kabupaten Tasikmalaya', label: 'Kabupaten Tasikmalaya', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kota Banjar', label: 'Kota Banjar', province: 'Jawa Barat', type: 'Kota' },
  { value: 'Kabupaten Ciamis', label: 'Kabupaten Ciamis', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Cianjur', label: 'Kabupaten Cianjur', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Garut', label: 'Kabupaten Garut', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Indramayu', label: 'Kabupaten Indramayu', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Karawang', label: 'Kabupaten Karawang', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Kuningan', label: 'Kabupaten Kuningan', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Majalengka', label: 'Kabupaten Majalengka', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Pangandaran', label: 'Kabupaten Pangandaran', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Purwakarta', label: 'Kabupaten Purwakarta', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Subang', label: 'Kabupaten Subang', province: 'Jawa Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Sumedang', label: 'Kabupaten Sumedang', province: 'Jawa Barat', type: 'Kabupaten' },

  // --- BANTEN ---
  { value: 'Kota Tangerang', label: 'Kota Tangerang', province: 'Banten', type: 'Kota' },
  { value: 'Kota Tangerang Selatan', label: 'Kota Tangerang Selatan', province: 'Banten', type: 'Kota' },
  { value: 'Kabupaten Tangerang', label: 'Kabupaten Tangerang', province: 'Banten', type: 'Kabupaten' },
  { value: 'Kota Serang', label: 'Kota Serang', province: 'Banten', type: 'Kota' },
  { value: 'Kabupaten Serang', label: 'Kabupaten Serang', province: 'Banten', type: 'Kabupaten' },
  { value: 'Kota Cilegon', label: 'Kota Cilegon', province: 'Banten', type: 'Kota' },
  { value: 'Kabupaten Lebak', label: 'Kabupaten Lebak', province: 'Banten', type: 'Kabupaten' },
  { value: 'Kabupaten Pandeglang', label: 'Kabupaten Pandeglang', province: 'Banten', type: 'Kabupaten' },

  // --- JAWA TENGAH ---
  { value: 'Kota Semarang', label: 'Kota Semarang', province: 'Jawa Tengah', type: 'Kota' },
  { value: 'Kabupaten Semarang', label: 'Kabupaten Semarang', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kota Surakarta (Solo)', label: 'Kota Surakarta (Solo)', province: 'Jawa Tengah', type: 'Kota' },
  { value: 'Kota Magelang', label: 'Kota Magelang', province: 'Jawa Tengah', type: 'Kota' },
  { value: 'Kabupaten Magelang', label: 'Kabupaten Magelang', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kota Pekalongan', label: 'Kota Pekalongan', province: 'Jawa Tengah', type: 'Kota' },
  { value: 'Kabupaten Pekalongan', label: 'Kabupaten Pekalongan', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kota Salatiga', label: 'Kota Salatiga', province: 'Jawa Tengah', type: 'Kota' },
  { value: 'Kota Tegal', label: 'Kota Tegal', province: 'Jawa Tengah', type: 'Kota' },
  { value: 'Kabupaten Tegal', label: 'Kabupaten Tegal', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Banyumas (Purwokerto)', label: 'Kabupaten Banyumas (Purwokerto)', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Batang', label: 'Kabupaten Batang', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Blora', label: 'Kabupaten Blora', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Boyolali', label: 'Kabupaten Boyolali', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Brebes', label: 'Kabupaten Brebes', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Cilacap', label: 'Kabupaten Cilacap', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Demak', label: 'Kabupaten Demak', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Grobogan', label: 'Kabupaten Grobogan', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Jepara', label: 'Kabupaten Jepara', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Karanganyar', label: 'Kabupaten Karanganyar', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Kebumen', label: 'Kabupaten Kebumen', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Kendal', label: 'Kabupaten Kendal', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Klaten', label: 'Kabupaten Klaten', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Kudus', label: 'Kabupaten Kudus', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Pati', label: 'Kabupaten Pati', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Pemalang', label: 'Kabupaten Pemalang', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Purbalingga', label: 'Kabupaten Purbalingga', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Purworejo', label: 'Kabupaten Purworejo', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Rembang', label: 'Kabupaten Rembang', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Sragen', label: 'Kabupaten Sragen', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Sukoharjo', label: 'Kabupaten Sukoharjo', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Temanggung', label: 'Kabupaten Temanggung', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Wonogiri', label: 'Kabupaten Wonogiri', province: 'Jawa Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Wonosobo', label: 'Kabupaten Wonosobo', province: 'Jawa Tengah', type: 'Kabupaten' },

  // --- DI YOGYAKARTA ---
  { value: 'Kota Yogyakarta', label: 'Kota Yogyakarta', province: 'DI Yogyakarta', type: 'Kota' },
  { value: 'Kabupaten Sleman', label: 'Kabupaten Sleman', province: 'DI Yogyakarta', type: 'Kabupaten' },
  { value: 'Kabupaten Bantul', label: 'Kabupaten Bantul', province: 'DI Yogyakarta', type: 'Kabupaten' },
  { value: 'Kabupaten Gunungkidul', label: 'Kabupaten Gunungkidul', province: 'DI Yogyakarta', type: 'Kabupaten' },
  { value: 'Kabupaten Kulon Progo', label: 'Kabupaten Kulon Progo', province: 'DI Yogyakarta', type: 'Kabupaten' },

  // --- JAWA TIMUR ---
  { value: 'Kota Surabaya', label: 'Kota Surabaya', province: 'Jawa Timur', type: 'Kota' },
  { value: 'Kota Malang', label: 'Kota Malang', province: 'Jawa Timur', type: 'Kota' },
  { value: 'Kabupaten Malang', label: 'Kabupaten Malang', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kota Batu', label: 'Kota Batu', province: 'Jawa Timur', type: 'Kota' },
  { value: 'Kota Kediri', label: 'Kota Kediri', province: 'Jawa Timur', type: 'Kota' },
  { value: 'Kabupaten Kediri', label: 'Kabupaten Kediri', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kota Madiun', label: 'Kota Madiun', province: 'Jawa Timur', type: 'Kota' },
  { value: 'Kabupaten Madiun', label: 'Kabupaten Madiun', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kota Blitar', label: 'Kota Blitar', province: 'Jawa Timur', type: 'Kota' },
  { value: 'Kabupaten Blitar', label: 'Kabupaten Blitar', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kota Mojokerto', label: 'Kota Mojokerto', province: 'Jawa Timur', type: 'Kota' },
  { value: 'Kabupaten Mojokerto', label: 'Kabupaten Mojokerto', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kota Pasuruan', label: 'Kota Pasuruan', province: 'Jawa Timur', type: 'Kota' },
  { value: 'Kabupaten Pasuruan', label: 'Kabupaten Pasuruan', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kota Probolinggo', label: 'Kota Probolinggo', province: 'Jawa Timur', type: 'Kota' },
  { value: 'Kabupaten Probolinggo', label: 'Kabupaten Probolinggo', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Sidoarjo', label: 'Kabupaten Sidoarjo', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Gresik', label: 'Kabupaten Gresik', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Banyuwangi', label: 'Kabupaten Banyuwangi', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Jember', label: 'Kabupaten Jember', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Bojonegoro', label: 'Kabupaten Bojonegoro', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Tuban', label: 'Kabupaten Tuban', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Lamongan', label: 'Kabupaten Lamongan', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Jombang', label: 'Kabupaten Jombang', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Nganjuk', label: 'Kabupaten Nganjuk', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Ngawi', label: 'Kabupaten Ngawi', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Magetan', label: 'Kabupaten Magetan', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Ponorogo', label: 'Kabupaten Ponorogo', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Pacitan', label: 'Kabupaten Pacitan', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Trenggalek', label: 'Kabupaten Trenggalek', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Tulungagung', label: 'Kabupaten Tulungagung', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Lumajang', label: 'Kabupaten Lumajang', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Bondowoso', label: 'Kabupaten Bondowoso', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Situbondo', label: 'Kabupaten Situbondo', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Bangkalan', label: 'Kabupaten Bangkalan', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Sampang', label: 'Kabupaten Sampang', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Pamekasan', label: 'Kabupaten Pamekasan', province: 'Jawa Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Sumenep', label: 'Kabupaten Sumenep', province: 'Jawa Timur', type: 'Kabupaten' },

  // --- BALI & NUSA TENGGARA ---
  { value: 'Kota Denpasar', label: 'Kota Denpasar', province: 'Bali', type: 'Kota' },
  { value: 'Kabupaten Badung', label: 'Kabupaten Badung', province: 'Bali', type: 'Kabupaten' },
  { value: 'Kabupaten Gianyar', label: 'Kabupaten Gianyar', province: 'Bali', type: 'Kabupaten' },
  { value: 'Kabupaten Tabanan', label: 'Kabupaten Tabanan', province: 'Bali', type: 'Kabupaten' },
  { value: 'Kabupaten Buleleng (Singaraja)', label: 'Kabupaten Buleleng (Singaraja)', province: 'Bali', type: 'Kabupaten' },
  { value: 'Kabupaten Karangasem', label: 'Kabupaten Karangasem', province: 'Bali', type: 'Kabupaten' },
  { value: 'Kabupaten Klungkung', label: 'Kabupaten Klungkung', province: 'Bali', type: 'Kabupaten' },
  { value: 'Kabupaten Bangli', label: 'Kabupaten Bangli', province: 'Bali', type: 'Kabupaten' },
  { value: 'Kabupaten Jembrana (Negara)', label: 'Kabupaten Jembrana (Negara)', province: 'Bali', type: 'Kabupaten' },
  { value: 'Kota Mataram', label: 'Kota Mataram', province: 'Nusa Tenggara Barat', type: 'Kota' },
  { value: 'Kota Bima', label: 'Kota Bima', province: 'Nusa Tenggara Barat', type: 'Kota' },
  { value: 'Kabupaten Lombok Barat', label: 'Kabupaten Lombok Barat', province: 'Nusa Tenggara Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Lombok Tengah', label: 'Kabupaten Lombok Tengah', province: 'Nusa Tenggara Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Lombok Timur', label: 'Kabupaten Lombok Timur', province: 'Nusa Tenggara Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Lombok Utara', label: 'Kabupaten Lombok Utara', province: 'Nusa Tenggara Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Sumbawa', label: 'Kabupaten Sumbawa', province: 'Nusa Tenggara Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Sumbawa Barat', label: 'Kabupaten Sumbawa Barat', province: 'Nusa Tenggara Barat', type: 'Kabupaten' },
  { value: 'Kota Kupang', label: 'Kota Kupang', province: 'Nusa Tenggara Timur', type: 'Kota' },
  { value: 'Kabupaten Manggarai Barat (Labuan Bajo)', label: 'Kabupaten Manggarai Barat (Labuan Bajo)', province: 'Nusa Tenggara Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Sikka (Maumere)', label: 'Kabupaten Sikka (Maumere)', province: 'Nusa Tenggara Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Ende', label: 'Kabupaten Ende', province: 'Nusa Tenggara Timur', type: 'Kabupaten' },

  // --- SUMATERA ---
  { value: 'Kota Medan', label: 'Kota Medan', province: 'Sumatera Utara', type: 'Kota' },
  { value: 'Kota Binjai', label: 'Kota Binjai', province: 'Sumatera Utara', type: 'Kota' },
  { value: 'Kota Pematangsiantar', label: 'Kota Pematangsiantar', province: 'Sumatera Utara', type: 'Kota' },
  { value: 'Kabupaten Deli Serdang', label: 'Kabupaten Deli Serdang', province: 'Sumatera Utara', type: 'Kabupaten' },
  { value: 'Kabupaten Karo (Berastagi)', label: 'Kabupaten Karo (Berastagi)', province: 'Sumatera Utara', type: 'Kabupaten' },
  { value: 'Kota Banda Aceh', label: 'Kota Banda Aceh', province: 'Aceh', type: 'Kota' },
  { value: 'Kota Sabang', label: 'Kota Sabang', province: 'Aceh', type: 'Kota' },
  { value: 'Kota Lhokseumawe', label: 'Kota Lhokseumawe', province: 'Aceh', type: 'Kota' },
  { value: 'Kota Padang', label: 'Kota Padang', province: 'Sumatera Barat', type: 'Kota' },
  { value: 'Kota Bukittinggi', label: 'Kota Bukittinggi', province: 'Sumatera Barat', type: 'Kota' },
  { value: 'Kota Payakumbuh', label: 'Kota Payakumbuh', province: 'Sumatera Barat', type: 'Kota' },
  { value: 'Kota Pekanbaru', label: 'Kota Pekanbaru', province: 'Riau', type: 'Kota' },
  { value: 'Kota Dumai', label: 'Kota Dumai', province: 'Riau', type: 'Kota' },
  { value: 'Kota Batam', label: 'Kota Batam', province: 'Kepulauan Riau', type: 'Kota' },
  { value: 'Kota Tanjungpinang', label: 'Kota Tanjungpinang', province: 'Kepulauan Riau', type: 'Kota' },
  { value: 'Kabupaten Bintan', label: 'Kabupaten Bintan', province: 'Kepulauan Riau', type: 'Kabupaten' },
  { value: 'Kota Jambi', label: 'Kota Jambi', province: 'Jambi', type: 'Kota' },
  { value: 'Kota Palembang', label: 'Kota Palembang', province: 'Sumatera Selatan', type: 'Kota' },
  { value: 'Kota Prabumulih', label: 'Kota Prabumulih', province: 'Sumatera Selatan', type: 'Kota' },
  { value: 'Kota Bengkulu', label: 'Kota Bengkulu', province: 'Bengkulu', type: 'Kota' },
  { value: 'Kota Bandar Lampung', label: 'Kota Bandar Lampung', province: 'Lampung', type: 'Kota' },
  { value: 'Kota Metro', label: 'Kota Metro', province: 'Lampung', type: 'Kota' },
  { value: 'Kabupaten Lampung Selatan', label: 'Kabupaten Lampung Selatan', province: 'Lampung', type: 'Kabupaten' },
  { value: 'Kota Pangkalpinang', label: 'Kota Pangkalpinang', province: 'Bangka Belitung', type: 'Kota' },

  // --- KALIMANTAN ---
  { value: 'Kota Balikpapan', label: 'Kota Balikpapan', province: 'Kalimantan Timur', type: 'Kota' },
  { value: 'Kota Samarinda', label: 'Kota Samarinda', province: 'Kalimantan Timur', type: 'Kota' },
  { value: 'Kota Bontang', label: 'Kota Bontang', province: 'Kalimantan Timur', type: 'Kota' },
  { value: 'Kabupaten Penajam Paser Utara (IKN)', label: 'Kabupaten Penajam Paser Utara (IKN)', province: 'Kalimantan Timur', type: 'Kabupaten' },
  { value: 'Kabupaten Kutai Kartanegara', label: 'Kabupaten Kutai Kartanegara', province: 'Kalimantan Timur', type: 'Kabupaten' },
  { value: 'Kota Banjarmasin', label: 'Kota Banjarmasin', province: 'Kalimantan Selatan', type: 'Kota' },
  { value: 'Kota Banjarbaru', label: 'Kota Banjarbaru', province: 'Kalimantan Selatan', type: 'Kota' },
  { value: 'Kota Pontianak', label: 'Kota Pontianak', province: 'Kalimantan Barat', type: 'Kota' },
  { value: 'Kota Singkawang', label: 'Kota Singkawang', province: 'Kalimantan Barat', type: 'Kota' },
  { value: 'Kota Palangka Raya', label: 'Kota Palangka Raya', province: 'Kalimantan Tengah', type: 'Kota' },
  { value: 'Kota Tarakan', label: 'Kota Tarakan', province: 'Kalimantan Utara', type: 'Kota' },

  // --- SULAWESI ---
  { value: 'Kota Makassar', label: 'Kota Makassar', province: 'Sulawesi Selatan', type: 'Kota' },
  { value: 'Kota Palopo', label: 'Kota Palopo', province: 'Sulawesi Selatan', type: 'Kota' },
  { value: 'Kota Parepare', label: 'Kota Parepare', province: 'Sulawesi Selatan', type: 'Kota' },
  { value: 'Kabupaten Gowa', label: 'Kabupaten Gowa', province: 'Sulawesi Selatan', type: 'Kabupaten' },
  { value: 'Kabupaten Maros', label: 'Kabupaten Maros', province: 'Sulawesi Selatan', type: 'Kabupaten' },
  { value: 'Kota Manado', label: 'Kota Manado', province: 'Sulawesi Utara', type: 'Kota' },
  { value: 'Kota Tomohon', label: 'Kota Tomohon', province: 'Sulawesi Utara', type: 'Kota' },
  { value: 'Kota Bitung', label: 'Kota Bitung', province: 'Sulawesi Utara', type: 'Kota' },
  { value: 'Kabupaten Minahasa Utara', label: 'Kabupaten Minahasa Utara', province: 'Sulawesi Utara', type: 'Kabupaten' },
  { value: 'Kota Palu', label: 'Kota Palu', province: 'Sulawesi Tengah', type: 'Kota' },
  { value: 'Kota Kendari', label: 'Kota Kendari', province: 'Sulawesi Tenggara', type: 'Kota' },
  { value: 'Kota Baubau', label: 'Kota Baubau', province: 'Sulawesi Tenggara', type: 'Kota' },
  { value: 'Kota Gorontalo', label: 'Kota Gorontalo', province: 'Gorontalo', type: 'Kota' },
  { value: 'Kabupaten Mamuju', label: 'Kabupaten Mamuju', province: 'Sulawesi Barat', type: 'Kabupaten' },

  // --- MALUKU & PAPUA ---
  { value: 'Kota Ambon', label: 'Kota Ambon', province: 'Maluku', type: 'Kota' },
  { value: 'Kota Ternate', label: 'Kota Ternate', province: 'Maluku Utara', type: 'Kota' },
  { value: 'Kota Tidore Kepulauan', label: 'Kota Tidore Kepulauan', province: 'Maluku Utara', type: 'Kota' },
  { value: 'Kota Jayapura', label: 'Kota Jayapura', province: 'Papua', type: 'Kota' },
  { value: 'Kabupaten Jayapura', label: 'Kabupaten Jayapura', province: 'Papua', type: 'Kabupaten' },
  { value: 'Kota Sorong', label: 'Kota Sorong', province: 'Papua Barat Daya', type: 'Kota' },
  { value: 'Kabupaten Manokwari', label: 'Kabupaten Manokwari', province: 'Papua Barat', type: 'Kabupaten' },
  { value: 'Kabupaten Merauke', label: 'Kabupaten Merauke', province: 'Papua Selatan', type: 'Kabupaten' },
  { value: 'Kabupaten Mimika (Timika)', label: 'Kabupaten Mimika (Timika)', province: 'Papua Tengah', type: 'Kabupaten' },
  { value: 'Kabupaten Jayawijaya (Wamena)', label: 'Kabupaten Jayawijaya (Wamena)', province: 'Papua Pegunungan', type: 'Kabupaten' },
];

/**
 * Normalizes city string for loose matching (e.g. "bekasi" -> "Kota Bekasi" or "Kabupaten Bekasi")
 */
export function findMatchingCity(query: string): CityOption | undefined {
  if (!query || !query.trim()) return undefined;
  const q = query.toLowerCase().trim();
  return INDONESIA_CITIES.find(
    (c) =>
      c.value.toLowerCase() === q ||
      c.label.toLowerCase().replace(/^(kota|kabupaten)\s+/, '') === q ||
      c.value.toLowerCase().includes(q)
  );
}
